version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: riders-postgres
        ports:
            - '6500:5432'
        volumes:
            - progresDB:/data/postgres
        env_file:
            - ./.env

    redis:
        image: redis:alpine
        container_name: riders-redis
        ports:
            - '6379:6379'
        volumes:
            - redisDB:/data
volumes:
    progresDB:
    redisDB:
